#pragma once

# define DAVIDSON_MAX_VECS 30
# define DAVIDSON_KEEP_DEFLATE 2

# define DEFAULT_SITESIZE 2
# define DEFAULT_SOLVER_TOL 1e-5
# define DEFAULT_SOLVER_MAX_ITS 100
# define DEFAULT_SWEEPS 4
# define DEFAULT_E_CONV 1e-6
